{
 "title": "Toxicity Detector Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logits Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(toxicity_detector_logits_distribution_bucket[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "HTTP Requests / Prediction Results Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(toxicity_detector_http_requests_total[1m])",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Execution Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(toxicity_detector_http_request_duration_seconds_sum[1m]) / rate(toxicity_detector_http_request_duration_seconds_count[1m])",
     "legendFormat": "Request"
    },
    {
     "expr": "rate(toxicity_detector_model_execution_duration_seconds_sum[1m]) / rate(toxicity_detector_model_execution_duration_seconds_count[1m])",
     "legendFormat": "Model"
    }
   ]
  },
  {
   "title": "Total Count Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "toxicity_detector_http_requests_total",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "toxicity_detector_active_http_requests",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Model Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "toxicity_detector_model_errors_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}