name: Build and push

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!**/README.md"
      - "!.github/**"
      - .github/workflows/docker.yml
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_LOGIN }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: |
            twirapp/toxicity-detector:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
